version: '3.4'

services:

  frontend:
    image: pizzafrontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: pizzabackend
    build: 
      context: Backend
      dockerfile: Dockerfile
    ports: 
      - "5900:80"